In [21]:
#Import necessary librarires

import pandas as pd
from datetime import timedelta

In [32]:

def process_customers():
    customers = pd.read_csv(r"C:\Users\Green Gen Tech\Downloads\Customers_data.csv", encoding='ISO-8859-1')
    print(f"raw_data:\n{customers.head()}\n")
    customers['Birthday'] = pd.to_datetime(customers['Birthday']).dt.date
    customers.drop('State Code', axis=1, inplace=True)
    customer_cleaned = customers.copy()
    customer_cleaned_path = r"C:\\Users\\Green Gen Tech\\Downloads\\Customer_data_cleaned.xlsx"
    customers.to_excel(customer_cleaned_path, index=False)
    print(f"Processed Customers:\n{customers.head()}\n")

def process_stores():
    stores = pd.read_csv(r"C:\Users\Green Gen Tech\Downloads\Stores_data.csv", encoding='ISO-8859-1')
    print(f"raw_data:\n{stores.head()}\n")
    stores['Open Date'] = pd.to_datetime(stores['Open Date'], errors='coerce')
    stores['Square Meters'] = stores['Square Meters'].fillna(0)
    stores_cleaned_path = r"C:\\Users\\Green Gen Tech\\Downloads\\stores_data_cleaned.xlsx"
    stores.to_excel(stores_cleaned_path, index=False)
    print(f"Processed Stores:\n{stores.head()}\n")

def process_exchange_rates():
    exchange_rate = pd.read_csv(r"C:\Users\Green Gen Tech\Downloads\Exchange_Rates_data.csv", encoding='ISO-8859-1')
    print("Initial DataFrame:")
    print(exchange_rate.head())
    print("Initial Data Types:")
    print(exchange_rate.dtypes)

    exchange_rate['Date'] = pd.to_datetime(exchange_rate['Date'], errors='coerce')
    print("DataFrame After Conversion:")
    print(exchange_rate.head())
    print("Data Types After Conversion:")
    print(exchange_rate.dtypes)

    excel_file_path = r"C:\\Users\\Green Gen Tech\\Downloads\\exchange_rates_data_cleaned.xlsx"
    exchange_rate.to_excel(excel_file_path, index=False)

    exchange_rate_loaded = pd.read_excel(excel_file_path)
    print("DataFrame After Loading from Excel:")
    print(exchange_rate_loaded.head())
    print("Data Types After Loading from Excel:")
    print(exchange_rate_loaded.dtypes)

def process_products():
    product = pd.read_csv(r"C:\Users\Green Gen Tech\Downloads\Products_data.csv")

    unit_cost_usd = []
    for value in product['Unit Cost USD']:
        if isinstance(value, str):
            # Remove '$', commas, and strip any spaces before converting to float
            unit_cost_usd.append(float(value.replace('$', '').replace(',', '').strip()))
        else:
            unit_cost_usd.append(value)
    product['Unit Cost USD'] = unit_cost_usd

    unit_price_usd = []
    for value in product['Unit Price USD']:
        if isinstance(value, str):
            # Remove '$', commas, and strip any spaces before converting to float
            unit_price_usd.append(float(value.replace('$', '').replace(',', '').strip()))
        else:
            unit_price_usd.append(value)
    product['Unit Price USD'] = unit_price_usd

    product['Unit Cost USD'].fillna(0, inplace=True)
    product['Unit Price USD'].fillna(0, inplace=True)

    product_cleaned_path = r"C:\\Users\\Green Gen Tech\\Downloads\\products_data_cleaned.xlsx"
    product.to_excel(product_cleaned_path, index=False)
    print(f"Processed Products:\n{product.head()}\n")


def process_sales():
    sales = pd.read_csv(r"C:\Users\\Green Gen Tech\Downloads\Sales_data.csv", encoding='ISO-8859-1')
    print(f"raw_data:\n{sales.head()}\n")
    sales['Order Date'] = pd.to_datetime(sales['Order Date'], errors='coerce')
    sales['Delivery Date'] = pd.to_datetime(sales['Delivery Date'], errors='coerce')
    
    sales['Difference'] = (sales['Delivery Date'] - sales['Order Date']).dt.days
    average_difference = sales['Difference'].mean()

    sales['Delivery Date'].fillna(sales['Order Date'] + pd.to_timedelta(average_difference, unit='days'), inplace=True)
    sales.drop(columns=['Difference'], inplace=True)

    sales_cleaned_path = r"C:\\Users\\Green Gen Tech\\Downloads\\Sales_data_cleaned.xlsx"
    sales.to_excel(sales_cleaned_path, index=False)
    print(f"Processed Sales:\n{sales.head()}\n")

def process_all_data():
    process_customers()
    process_stores()
    process_exchange_rates()
    process_products()
    process_sales()

# Run the function to process all data
process_all_data()

raw_data:
   CustomerKey  Gender               Name            City State Code  \
0          301  Female      Lilly Harding  WANDEARAH EAST         SA
1          325  Female       Madison Hull      MOUNT BUDD         WA
2          554  Female      Claire Ferres       WINJALLOK        VIC
3          786    Male  Jai Poltpalingada    MIDDLE RIVER         SA
4         1042    Male    Aidan Pankhurst   TAWONGA SOUTH        VIC

               State Zip Code    Country  Continent    Birthday
0    South Australia     5523  Australia  Australia    7/3/1939
1  Western Australia     6522  Australia  Australia   9/27/1979
2           Victoria     3380  Australia  Australia   5/26/1947
3    South Australia     5223  Australia  Australia   9/17/1957
4           Victoria     3698  Australia  Australia  11/19/1965

Processed Customers:
   CustomerKey  Gender               Name            City              State  \
0          301  Female      Lilly Harding  WANDEARAH EAST    South Australia
1          325  Female       Madison Hull      MOUNT BUDD  Western Australia
2          554  Female      Claire Ferres       WINJALLOK           Victoria
3          786    Male  Jai Poltpalingada    MIDDLE RIVER    South Australia
4         1042    Male    Aidan Pankhurst   TAWONGA SOUTH           Victoria

  Zip Code    Country  Continent    Birthday
0     5523  Australia  Australia  1939-07-03
1     6522  Australia  Australia  1979-09-27
2     3380  Australia  Australia  1947-05-26
3     5223  Australia  Australia  1957-09-17
4     3698  Australia  Australia  1965-11-19

raw_data:
   StoreKey    Country                         State  Square Meters  \
0         1  Australia  Australian Capital Territory          595.0
1         2  Australia            Northern Territory          665.0
2         3  Australia               South Australia         2000.0
3         4  Australia                      Tasmania         2000.0
4         5  Australia                      Victoria         2000.0

    Open Date
0  01-01-2008
1  01-12-2008
2  01-07-2012
3  01-01-2010
4  12-09-2015

Processed Stores:
   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0 2008-01-01
1         2  Australia            Northern Territory          665.0 2008-01-12
2         3  Australia               South Australia         2000.0 2012-01-07
3         4  Australia                      Tasmania         2000.0 2010-01-01
4         5  Australia                      Victoria         2000.0 2015-12-09

Initial DataFrame:
       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415
Initial Data Types:
Date         object
Currency     object
Exchange    float64
dtype: object
DataFrame After Conversion:
        Date Currency  Exchange
0 2015-01-01      USD    1.0000
1 2015-01-01      CAD    1.1583
2 2015-01-01      AUD    1.2214
3 2015-01-01      EUR    0.8237
4 2015-01-01      GBP    0.6415
Data Types After Conversion:
Date        datetime64[ns]
Currency            object
Exchange           float64
dtype: object
DataFrame After Loading from Excel:
        Date Currency  Exchange
0 2015-01-01      USD    1.0000
1 2015-01-01      CAD    1.1583
2 2015-01-01      AUD    1.2214
3 2015-01-01      EUR    0.8237
4 2015-01-01      GBP    0.6415
Data Types After Loading from Excel:
Date        datetime64[ns]
Currency            object
Exchange           float64
dtype: object

C:\Users\Green Gen Tech\AppData\Local\Temp\ipykernel_3984\3587929612.py:66: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  product['Unit Cost USD'].fillna(0, inplace=True)
C:\Users\Green Gen Tech\AppData\Local\Temp\ipykernel_3984\3587929612.py:67: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  product['Unit Price USD'].fillna(0, inplace=True)

Processed Products:
   ProductKey                         Product Name    Brand   Color  \
0           1  Contoso 512MB MP3 Player E51 Silver  Contoso  Silver
1           2    Contoso 512MB MP3 Player E51 Blue  Contoso    Blue
2           3     Contoso 1G MP3 Player E100 White  Contoso   White
3           4    Contoso 2G MP3 Player E200 Silver  Contoso  Silver
4           5       Contoso 2G MP3 Player E200 Red  Contoso     Red

   Unit Cost USD  Unit Price USD  SubcategoryKey Subcategory  CategoryKey  \
0           6.62           12.99             101     MP4&MP3            1
1           6.62           12.99             101     MP4&MP3            1
2           7.40           14.52             101     MP4&MP3            1
3          11.00           21.57             101     MP4&MP3            1
4          11.00           21.57             101     MP4&MP3            1

  Category
0    Audio
1    Audio
2    Audio
3    Audio
4    Audio

raw_data:
   Order Number  Line Item Order Date Delivery Date  CustomerKey  StoreKey  \
0        366000          1   1/1/2016           NaN       265598        10
1        366001          1   1/1/2016     1/13/2016      1269051         0
2        366001          2   1/1/2016     1/13/2016      1269051         0
3        366002          1   1/1/2016     1/12/2016       266019         0
4        366002          2   1/1/2016     1/12/2016       266019         0

   ProductKey  Quantity Currency Code
0        1304         1           CAD
1        1048         2           USD
2        2007         1           USD
3        1106         7           CAD
4         373         1           CAD

C:\Users\Green Gen Tech\AppData\Local\Temp\ipykernel_3984\3587929612.py:83: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales['Delivery Date'].fillna(sales['Order Date'] + pd.to_timedelta(average_difference, unit='days'), inplace=True)

Processed Sales:
   Order Number  Line Item Order Date                 Delivery Date  \
0        366000          1 2016-01-01 2016-01-05 12:41:56.855298140
1        366001          1 2016-01-01 2016-01-13 00:00:00.000000000
2        366001          2 2016-01-01 2016-01-13 00:00:00.000000000
3        366002          1 2016-01-01 2016-01-12 00:00:00.000000000
4        366002          2 2016-01-01 2016-01-12 00:00:00.000000000

   CustomerKey  StoreKey  ProductKey  Quantity Currency Code
0       265598        10        1304         1           CAD
1      1269051         0        1048         2           USD
2      1269051         0        2007         1           USD
3       266019         0        1106         7           CAD
4       266019         0         373         1           CAD